version: '3'

services:
    codebert:
        container_name: ARSeek
        build: .
        # runtime: nvidia
        deploy:
            resources:
              reservations:
                devices:
                - driver: nvidia
                  count: all
                  capabilities: [gpu]
        ports:
            - "9292:9292"
        volumes:
            - ./:/app/ARSeek
        tty: true


